name: CrossGPT QA Analysis
run-name: ${{ github.actor }} is testing with CrossGPT
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code and clone to runner.
        uses: actions/checkout@v4
      - name: Creating virtual environment and installing dependenies.
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      - name: Initialize Access Keys
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.GITHUBACTIONSTWO }}"
      - name: Running FastAPI
        run: |
          fastapi run run.py
  testing:
    needs: setup # Dependant on the setup job function
    runs-on: ubuntu-latest
    steps:
      - name: Grabbing CrossGPT code.
        uses: actions/checkout@master
        with:
          repository: DunkJFunk/TestApp
          ref: refs/heads/main
      - name: Creating virtual environment and installing dependenies.
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      - name: List GPT files.
        run: |
          ls -a
      - name: Execute API Call
        run: |
          python main.py
# Setup Instance
#   - Check out repository code
#   - Make sure the repository is able to receive calls from the runner
#     - Creating and activating .venv file
#     - Running 'fastapi run' inside of the container through bash or zsh
#   - Access the necessary files inside of the repository (.html)
# Running Tests
#   - Be able to access CrossGPT (a.k.a. a seperate public repository)
#   - Call the main.py function with our desired variables (FILE1 and FILE2)